name = "Ennui's Bigger Intro"
author = "Ennui Langeweile"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f33731bf681f5f5a9460c5f0cfee3688d17fed399d5c821831b2f1479b99f55c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
