# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
# oh boy i better Call Saul (LodestoneLib's fault)
phrases = ["jesser where is the cocainer"]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = []
